# Generated by Django 4.0.2 on 2022-05-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deffect_detect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardexample',
            name='photo',
            field=models.ImageField(upload_to='example_boards/'),
        ),
    ]
